### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by arif98741** [arafat-web/Bulk-Email-Sender#1]
You have done a good job. I am concern about if anyone upload 1000mails using excel and based on your code this will loop through 1000times. But due to server resources, this will become timeout and stopped. You should implement job and queue here for solving this issue

https://github.com/arafat-web/Bulk-Email-Sender/blob/e300cfde281601b416bde0ba16ba4cc8f6f01dad/app/Http/Controllers/OneTimeSenderController.php#L45

**Comment by arafat-web** [comment]
solved! Thanks for your contribution.
